name: 'Build Image'

on:
  workflow_dispatch:
    inputs:
      skip_publish:
        description: 'Skip the publish steps at the end'
        required: false
        default: 'false'
  push:
    tags: 
      - v*

jobs:
  build_image:
    name: 'Build Raspberry OS Image'
    runs-on: 'ubuntu-latest'
    
    steps:
    
    - name: 'Checkout Repo'
      uses: actions/checkout@v2
    
    - name: 'Checkout RPi-Gen'
      uses: actions/checkout@v2
      with:
        repository: 'RPi-Distro/pi-gen'
        path: 'pi-gen-files/pi-gen'
  
    - name: 'Setup QEMU Static'
      uses: docker/setup-qemu-action@v1
      id: qemu

    - name: 'Prepare stages'
      working-directory: 'pi-gen-files/pi-gen'
      run: |
        touch ./stage2/SKIP_IMAGES
        cp -r ../{config,trainer_base,evocortex_ros} ./
        if [[ "${GITHUB_EVENT_NAME}" = "push" ]]; then
          echo "IMG_FILENAME=\${IMG_NAME}-$(basename ${GITHUB_REF})" >>config
          echo "ZIP_FILENAME=\${IMG_FILENAME}" >>config
        fi

    - name: 'Do Build'
      working-directory: 'pi-gen-files/pi-gen'
      run: |
        sudo ./build-docker.sh -c config
        rm deploy/*.img || true

    - name: 'Store resulting Image'
      uses: actions/upload-artifact@v2
      with:
        name: 'Images'
        path: |
          pi-gen-files/pi-gen/deploy/*.zip

    - name: 'Upload to FTP'
      uses: wangyucode/sftp-upload-action@v1.1
      with:
        host: ${{ secrets.FTP_SERVER }}
        port: 22
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        localdir: 'pi-gen-files/pi-gen/deploy'
        remotedir: '/evo_trainer_images/'
        dryRun: true
      if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.skip_publish != 'true' }}

