name: 'Build Image'

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/build-image.yml'
    - 'image-files/**'
  pull_request:
    branches:
    - 'master'
    paths:
    - '.github/workflows/build-image.yml'
    - 'image-files/**'

jobs:
  build_image:
    name: 'Build Raspberry OS Image'
    runs-on: 'ubuntu-latest'
    
    steps:
    
    - name: 'Checkout Repo'
      uses: actions/checkout@v2
    
    - name: 'Checkout RPi-Gen'
      uses: actions/checkout@v2
      with:
        repository: 'RPi-Distro/pi-gen'
        path: 'pi-gen-files/pi-gen'
  
    - name: 'Setup QEMU Static'
      uses: docker/setup-qemu-action@v1
      id: qemu

    - name: 'Prepare stages'
      working-directory: 'pi-gen-files/pi-gen'
      run: |
        touch ./stage2/SKIP_IMAGES
        cp -a ../config ./config
        cp -a ../custom_stage ./custom_stage

    - name: 'Do Build'
      working-directory: 'pi-gen-files/pi-gen'
      run: |
        sudo ./build-docker.sh -c config

    - name: 'Store resulting Image'
      uses: actions/upload-artifact@v2
      with:
        name: 'Images'
        path: |
          pi-gen-files/pi-gen/deploy/*.img
          pi-gen-files/pi-gen/deploy/*.zip

